### ISSUE TITLE
Cannot find pkg-package 'sox'

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.io.audio#1]
When I build the package, I get the error that
```
RuntimeError: pkg-config package `sox' was not found
```
I tried to install the``sox`` package using
```
sudo apt-get install sox
```
which succeeded, but the error remains. 
Which is the correct package to install to get ``sox`` running? Should we add that to the installation instructions of this package, or even to the global Bob installation instructions?

**Comment by anjos** [comment]
You should install `libsox-dev` instead.
